# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: baidu_speed@ziye3

on:
    workflow_dispatch:
    schedule:
      - cron: "0,30 * * * *"
    watch:
      types: [started]
    repository_dispatch:
      types: baidu_speed

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
          
      - name: '运行 【百度极速版】'
        run: |
          node Task/baidu_speed.js
        
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BAIDU_CASH : ${{ secrets.BAIDU_CASH }}
          BAIDU_COOKIE: ${{ secrets.BAIDU_COOKIE }}
